# -*- coding: utf-8 -*-
"""modélisation RSI + MACD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135GnG66l6qq_Nb1rWcE2FtZvpBdoOse3
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Récupérer les données historiques des prix de l'action TotalEnergies
ticker = "ACA.PA"  # Le symbole boursier de TotalEnergies
start_date = "2020-01-01"
end_date = "2023-08-04"
data = yf.download(ticker, start=start_date, end=end_date)

# Calculer les moyennes mobiles exponentielles (EMA)
data['EMA12'] = data['Close'].ewm(span=12, adjust=False).mean()
data['EMA26'] = data['Close'].ewm(span=26, adjust=False).mean()

# Calculer la ligne MACD
data['MACD'] = data['EMA12'] - data['EMA26']

# Calculer la ligne de signal (Signal Line)
data['Signal_Line'] = data['MACD'].ewm(span=9, adjust=False).mean()

# Calculer le RSI
data['RSI'] = 100 - (100 / (1 + (data['Close'].diff(1).fillna(0)).rolling(window=14, min_periods=1).apply(lambda x: x[x > 0].mean()) / (data['Close'].diff(1).fillna(0)).rolling(window=14, min_periods=1).apply(lambda x: -x[x < 0].mean())))

# Tracer les graphiques
fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 18), sharex=True)

# Graphique MACD
ax1.plot(data.index, data['MACD'], label='MACD', color='blue')
ax1.plot(data.index, data['Signal_Line'], label='Signal Line', color='red')
ax1.bar(data.index, data['MACD'] - data['Signal_Line'], label='Histogram', color='gray')
ax1.set_ylabel('Value')
ax1.legend()
ax1.grid(True)

# Graphique RSI
ax2.plot(data.index, data['RSI'], label='RSI', color='green')
ax2.set_ylabel('Value')
ax2.legend()
ax2.grid(True)

# Graphique du cours de l'action
ax3.plot(data.index, data['Close'], label='Close', color='purple')
ax3.set_xlabel('Date')
ax3.set_ylabel('Price')
ax3.legend()
ax3.grid(True)

plt.suptitle('Inidcateurs techniques pour Crédit Agricole')
plt.show()